{"uuid": "45ba0d6f-80e2-48cf-b520-a8ff70375a9b", "children": ["74d25ba7-fe33-4e32-a82e-11bd5376794b", "a00ed0c8-e301-4ba0-8641-92a6fb4fc761"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'testfailed'\n", "trace": "  File \"/Users/bobit/PycharmProjects/AppiumPOMFramework/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/bobit/PycharmProjects/AppiumPOMFramework/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/bobit/PycharmProjects/AppiumPOMFramework/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/bobit/PycharmProjects/AppiumPOMFramework/tests/conftest.py\", line 13, in beforeClass\n    failed_before = request.session.testfailed\n"}, "start": 1593914288189, "stop": 1593914299070}], "start": 1593914288189, "stop": 1593914299085}